### ISSUE TITLE
Mousewheel scrolling in firefox is very slow

### ISSUE THREAD

**Issue by mecapetr** [idiotWu/angular-smooth-scrollbar#3]
Everything works perfect, but only in Firefox, the mousewheel scrolling is very slow.

**Comment by idiotWu** [comment]
I guess you are using Firefox on windows. On this version of Firefox, it will scroll by delta mode of `DOM_DELTA_LINE` [(ref here)](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/deltaMode).

This bug has been fixed since version v0.3.9, try update your scrollbar and see whether the problem is resolved.

**Comment by mecapetr** [comment]
I have tried to update my code to v0.4.0 but when I call ScrollbarService.getInstance, there is an error "n.resolve is not a function". I am using AngularJS v1.3.15.

**Comment by idiotWu** [comment]
Could you please provide more some code example about the error? I tried run the module with angular@1.3.15, but everything worked as expected.

**Comment by idiotWu** [comment]
This module supports [angular 1.4.3 and above](https://github.com/idiotWu/angular-smooth-scrollbar/blob/master/bower.json#L30).

In angular 1.3.x, `$q` api is slightly different from [Promises/A+](https://promisesaplus.com/) standard, it used `$q.when` instead of `$q.resolve`, so the error occurs.

I can, however, change my code to adapt to angular 1.3.x, but I can't see any benefit from doing that.

**Comment by idiotWu** [comment]
Anyway, I made a little fix in https://github.com/idiotWu/angular-smooth-scrollbar/commit/08dd9a87ab9a67910588b971a08a3fa829ce516b. Try update to version v0.4.1 :)

**Comment by mecapetr** [comment]
I have tried it and now everything works like a charm. Thank you very much :)
